#!/bin/bash
#SBATCH --account=rrg-jeffchen
#SBATCH --time=00:05:00
#SBATCH --ntasks=2
#SBATCH --mem-per-cpu=256M
source /home/walterms/py374/bin/activate
srun python -u mk_node_coords.py --runname=$1 --disable_tqdm=True 
